pub(crate) mod application_ports;
pub(crate) mod bsl_outline;
pub(crate) mod bundled_tools;
pub(crate) mod code_intelligence;
pub(crate) mod format_guard;
pub mod internal_adapters;
pub(crate) mod metadata_kinds;
pub(crate) mod metadata_operations;
pub mod native_operations;
pub mod path_policy;
pub(crate) mod platform;
pub(crate) mod platform_xml_owner;
pub(crate) mod platform_xml_resources;
pub(crate) mod platform_xml_roots;
// This foundational provider is consumed by the public migration in the next slice.
#[allow(dead_code)]
pub(crate) mod platform_xml_source_targets;
pub mod plugin_runtime;
pub(crate) mod project_sources;
pub(crate) mod redaction;
pub(crate) mod rlm_navigation;
pub(crate) mod runtime_jobs;
pub(crate) mod source_roots;
pub(crate) mod support_guard;
pub(crate) mod tool_context;
pub(crate) mod workspace;
pub mod workspace_index;
pub mod workspace_services;
pub mod workspace_state;
